### ISSUE TITLE
[Feature] Some Navigation suggestions

### ISSUE THREAD

**Issue by ylorgat** [faloker/purify#102]
**Is your feature request related to a problem? Please describe.**
Implement some navigation that would make the User ever so slightly better. 

The Project Name in the main homepage overview is currently not clickable. Clicking the name of the project should take you to the overview of the project.

Also the title "Purify" in the top left corner is not clickable where as the Logo is. Clicking this should take you back to the homepage.

![](https://cdn.discordapp.com/attachments/755565614864662550/760051446405791764/Screenshot_2020-09-28_at_09.12.52.png)

Thank you very much 😄

**Comment by ylorgat** [comment]
Thank you 😃

**Comment by faloker** [comment]
Merged into develop branch and will be released as part of version 1.1.0.
