### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ylorgat** [faloker/purify#115]
**Describe the bug**
If the Severity of the Bug is "Information" Purify does not catch this and maps the Medium Severity against it

**To Reproduce**
Submit a report where the severity is "Information"

**Expected behavior**
Severity is marked as Info

Thank you very much 

![Screenshot 2020-10-27 at 15 37 34](https://user-images.githubusercontent.com/35497024/97324977-611fb500-186a-11eb-9c3a-289e71dab42f.png)

**Comment by ylorgat** [comment]
As mentioned in our conversation a default severity of Medium might be too high and might cause false alarms on first glance of a ticket,

Defaulting to Info might be the best way to go as the User can then go in and adjust appropriately. This is mainly if a user uses a tool that uses a severity scale that is not supported by Purify.

Thank you very much :)

**Comment by faloker** [comment]
Released as part of v1.1.3
