### ISSUE TITLE
Login should only be available when not logged in

### ISSUE THREAD

**Issue by PhyberApex** [faloker/purify#12]
Currently you can get to the "welcome" page even if you are logged in. This does not make a lot of sense from a usability standpoint. This route should be blocked for logged in users. Also a log out button should be available.

PR appreciated?

~Cheers

**Comment by faloker** [comment]
Hi @PhyberApex,

I cannot but agree that this should work as you mentioned. This is currently part of my roadmap, and I will be able to implement it in a few days. And it will be part of the new mini-profile view for accumulating other options, not just logging out.

**Comment by faloker** [comment]
Stack with changes https://purify-develop.herokuapp.com/
