### ISSUE TITLE
perfops-rom: what's that about?

### ISSUE THREAD

**Issue by dmspils** [faloker/purify#29]
There's an async load of `perfops-rom` in `index.html`. I haven't come across perfops before but it looks like it's some sort of user monitoring service that tries to connect to a bunch of crazy sounding domains. Should that be in the prod release as disabling it (via CSP) seems to have no impact on operation of purify?

**Comment by faloker** [comment]
Yes, this script can be removed and it will not impact Purify operational status.

This script is part of [jsdelivr](https://github.com/jsdelivr/jsdelivr). In short, it collects performance metrics, you can read more about it [here](https://github.com/jsdelivr/jsdelivr#contribute-performance-data).

**Comment by dmspils** [comment]
Thanks, I've CSPd it out and Purify works ok so will look to include that in my fork.
