### ISSUE TITLE
User management/admin

### ISSUE THREAD

**Issue by dmspils** [faloker/purify#37]
Thinking about how the tool can integrate into our enterprise environment and the associated user management/auth options, I'm not intending to use LDAP so that's not an option but SSO (OAUTH/SAML) could be a good long term future feature.

However, in the short term, the 'Account Settings' button under my profile (top right of the page), doesn't seem to do anything at the mo, is that correct?

The further question is therefore: is there a concept of an admin role within the tool currently who can create/modify/delete users? In the short term, I'd like to disable user registration and just manually create users via an admin role so if that's possible it would be great to hear about it.

**Comment by faloker** [comment]
Hey @dmspils,

Currently, the tool lacks the concept of an administrator role, as well as any kind of user and role management.

But SSO is a good option for user authentication. There is a build with SSO support via SAML, it is available as a docker `feature-sso-login` tag. I also added instructions for setting it up, you can see them [here](https://faloker.gitbook.io/purify/sso).

For testing purposes, I used Auth0 as IdP, and it works pretty well. I cannot ask, but I would like to hear if the current implementation of SSO will work with your environment.

**Comment by dmspils** [comment]
Apologies, I did mean to reply. I currently use client cert auth in nginx to ensure that only people from my company can get to purify and we do have our own IdP but integrating with it would be a big piece of work which I'll only do if we productionise it's use (I'm currently testing). Being able to control (allowlist) users  and assign permissions to projects would be super cool though so maybe it's something I'll ask one our devs to look in to if you fancy some contributions.
