### ISSUE TITLE
refresh token issue

### ISSUE THREAD

**Issue by dmspils** [faloker/purify#76]
I'm not 100% sure I've diagnosed this one but thought I'd raise it to see if you've noticed similar.

Since one of the last updates, I've noticed that my session seems to expire at random intervals when using the GUI. Sometimes it'll be left dormant for half an hour and will expire, ok but not respecting the session duration, other times I'll be mid activity and will see a red unauthorised banner at the top RHS of the page and will be redirected back to login. But it's hard to pinpoint exactly what is causing it.

Looking at my cookies, I had two refresh tokens set for the session. I'm not entirely sure how I got two set but I assume that the browser if flip flopping between the two and causing random session expiries.

I did have a theory that it was related to my use of the API e.g. requesting a new API key maybe expiring the session in the UI somehow, but I can't replicate that.

Have you seen anything similar?

**Comment by faloker** [comment]
Hey @dmspils, 

sorry for the delay, I was unable to reproduce the mentioned issue, it may have been a cookie collision of the refresh tokens, idk. But it works as follows - 12 minutes after logging in, your browser will try to update the current access token and install a new refresh token, this has nothing to do with API keys.

It would be great if you could update to the latest version and lmk if the same behavior is seen again. Thanks!
